apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lighthouse-github-actions
  namespace: lighthouse-bandicoot
  description: Custom Github Actions for the Lighthouse Internal Developer Portal
  title: 'Techdocs Repository'
  links:
    - url: https://github.com/department-of-veterans-affairs/lighthouse-github-actions
      title: Lighthouse Github Actions
      icon: web
    - url: https://github.com/department-of-veterans-affairs/lighthouse-github-actions/issues
      title: Issues
      icon: help
    - url: https://lighthouseva.slack.com/archives/C020ZR4UL8H
      title: lighthouse-bandicoot slack
      icon: slack
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/department-of-veterans-affairs/lighthouse-github-actions
    github.com/project-slug: department-of-veterans-affairs/lighthouse-github-actions
spec:
  type: repository
  lifecycle: experimental
  owner: lighthouse-bandicoot
