apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: new-example-component
  description: An example component for Backstage catalog 
  annotations:
    github.com/project-slug: department-of-veterans-affairs/lighthouse-backstage-actions
spec:
  type: website
  lifecycle: experimental
  owner: lighthouse-bandicoot
