apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: new-example-component
  description: An example component for Backstage catalog 
  annotations:
    github.com/project-slug: lighthouse-backstage-example
  tags:
    - Backstage
    - Component
    - Example
  links:
    - url: https://backstage.io/docs/features/software-catalog/descriptor-format
      title: Backstage Documentation
      icon: dashboard
spec:
  type: website
  lifecycle: experimental
  owner: team-bandicoot
