apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lighthouse-github-actions
  namespace: lighthouse-bandicoot
  description: Github Repository for Lighthouse Github Actions
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/department-of-veterans-affairs/lighthouse-github-actions
    github.com/project-slug: department-of-veterans-affairs/lighthouse-github-actions
spec:
  type: repository
  lifecycle: experimental
  owner: lighthouse-bandicoot
