apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lighthouse-github-actions
  description: Github Actions to generate TechDocs for the Lighthouse Internal Developer Portal
  title: "Techdocs Repository"
  tags:
    - lighthouse
    - documentation
    - techdocs
    - docs
  links:
    - url: https://github.com/department-of-veterans-affairs/lighthouse-github-actions
      title: Lighthouse Github Actions
      icon: web
    - url: https://github.com/department-of-veterans-affairs/lighthouse-github-actions/issues
      title: Issues
      icon: help
    - url: https://lighthouseva.slack.com/archives/C020ZR4UL8H
      title: lighthouse-bandicoot slack
      icon: slack
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: department-of-veterans-affairs/lighthouse-github-actions
spec:
  type: repository
  lifecycle: experimental
  owner: lighthouse-bandicoot
