site_name: 'Lighthouse Github Actions Documentation'
repo_url: 'https://github.com/department-of-veterans-affairs/lighthouse-github-actions'
nav:
  - Home: index.md
  - Test: ../README.md
plugins:
  - techdocs-core
