plugins: [techdocs-core, section-index]
repo_url: https://github.com/department-of-veterans-affairs/lighthouse-github-actions
site_name: Lighthouse Github Actions Documentation
markdown_extensions:
  - pymdownx.snippets:
      check_paths: true
nav:
  - index.md
