name: "Publish Techdocs"
description: "Generates and publishes techdocs using kubernetes job"
inputs:
  kubeconfig:
    description: "Kubernetes context -- config file usually located at ~/.kube/config"
    required: true
  kube_namespace:
    description: "Namespace to use for Kubernetes job"
    default: "default"
    required: false
  serviceAccountName:
    description: "Service account name"
    required: true
  repository:
    description: "Name of repository"
    required: true
  namespace:
    description: "Namespace of entity; used as namespace for --entity <namespace/kind/name>"
    default: "default"
    required: false
  kind:
    description: "Kind of entity; used as kind for --entity <namespace/kind/name>"
    required: false
  name:
    description: "Name of Entity; used as name for --entity <namespace/kind/name>"
    required: false
  username:
    description: "Username used for GHCR authentication"
    default: ${{ github.repository_owner }}
    required: false
  token:
    description: "Token used for GHCR authentication"
    default: ${{ github.token }}
    required: false
  descriptor-file:
    description: "Name of catalog entity descriptor file"
    required: false
  AWSBucketName:
    description: "Name of the S3 Bucket to store generated Techdocs"
    default: "embark-techdocs-storage-nonprod"
    required: true
  PAT:
    description: "Personal access token for github"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2.4.0
      with:
        repository: ${{ inputs.repository }}
        token: ${{ inputs.token }}
    - name: Set K8s context
      uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ inputs.kubeconfig }}
    - name: Set kube namespace
      run: kubectl config set-context --current --namespace=${{ inputs.kube_namespace }}
      shell: bash
    - name: Get entity triplet
      id: entity
      env:
        BASE_PATH: ${{ github.workspace }}
        FILE: ${{ inputs.descriptor-file }}
        KIND: ${{ inputs.kind }}
        NAME: ${{ inputs.name }}
      run: >
        /bin/bash ${{ github.action_path }}/scripts/entity-triplet.sh
      shell: bash
    - name: Check triplet
      run: |
        echo "$namespace"
        echo "$kind"
        echo "$name"
      shell: bash
    - name: Validating Techdocs Location for Catalog Entity
      run: |
        if [[ "$namespace" == "null" ]]; then
          echo "Error: cannot create Techdocs with this Entity's namespace. Please add a valid namespace for the Entity."
        fi
        if [[ "$kind" == "null" ]]; then
          echo "Error: cannot create Techdocs with this Entity's Kind. Please add a valid Kind for the Entity."
        fi
        if [[ "$name" == "null" ]]; then
          echo "Error: cannot create Techdocs with this Entity's Name. Please add a valid Name for the Entity."
        fi
        echo "Entity's Techdocs Location: ${{ steps.entity.outputs.namespace }}/${{ steps.entity.outputs.kind }}/${{ steps.entity.outputs.name }}"
      shell: bash
    - name: Create Dockerconfigjson
      run: >
        ${{ github.action_path }}/scripts/create-dockerconfigjson.sh
        "${{ inputs.repository }}"
      env:
        GITHUB_TOKEN: ${{ inputs.PAT }}
        GITHUB_USER: ${{ github.repository_owner }}
      shell: bash
    - name: Create techdocs Job
      run: >
        ${{ github.action_path }}/scripts/create-techdocs-job.sh
        "${{ inputs.serviceAccountName }}"
        "${{ inputs.repository }}"
        "$namespace"
        "$kind"
        "$name"
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        GITHUB_USER: ${{ inputs.username }}
        S3_BUCKET_NAME: ${{ inputs.AWSBucketName }}
      shell: bash
    - name: Techdocs Job status
      run: >
        ${{ github.action_path }}/scripts/techdocs-job-status.sh "${{ inputs.repository }}"
      shell: bash
