name: "Send Techdocs Webhook"
description: "Sends a webhook to trigger repository dispatch event for techdocs workflow"
inputs:
  event:
    description: "Event trigger"
    default: "techdocs"
    required: false
  repository:
    description: "Name of repository"
    required: true
  branch:
    description: "Branch of repository"
    required: false
  descriptor-file:
    description: "Name of catalog entity descriptor file"
    required: false
  namespace:
    description: "Namespace of entity; used as namespace for --entity <namespace/kind/name>"
    default: "default"
    required: false
  token:
    description: "Personal Access token for webhook"
    required: false
  tag:
    description: "Tag or Commit sha for techdocs job version"
    default: "main"
    required: false
  gh-pages:
    description: "Flag used to enable gh-pages deployment"
    default: ""
    required: false
  strict-mode:
    description: "Flag used to enable or disable strict mode"
    default: "true"
    required: false
  enable-production:
    description: "Flag used to enable or disable techdocs for production"
    default: "true"
    required: false
runs:
  using: "composite"
  steps:
    - name: run test-in-another-repo
      id: get_status
      uses: stinkyfingers/cross-repo-dispatch@52c5ff3cc7277612c058d932896ac665f77ec249
      with:
        owner: "department-of-veterans-affairs"
        repo: "lighthouse-github-actions"
        ref: ${{ github.ref }}
        pat: ${{ inputs.token }}
        user: ${{ github.repository_owner }}
        sha: ${{ github.sha }}
        event_type: "techdocs"
        client_payload: '{"github": ${{ toJson(github) }}, "inputs": ${{ toJson(inputs) }}}'
        workflow_status_timeout: 1200
    - name: Display Results
      run: |
        echo "Status: ${{ steps.get_status.outputs.status }}"
        echo "Conclusion: ${{ steps.get_status.outputs.conclusion }}"
        echo "Html url: ${{ steps.get_status.outputs.html_url }}"
        if [ "${{ steps.get_status.outputs.conclusion }}" = "failure" ]; then exit 1; fi
      shell: bash
