name: 'Send Techdocs Webhook'
description: 'Sends a webhook to trigger repository dispatch event for techdocs workflow'
inputs:
  event:
    description: 'Event trigger'
    required: false
    default: 'techdocs'
  repository:
    description: 'Name of repository'
    required: true
  descriptor-file:
    description: 'Name of catalog entity descriptor file'
    required: false
  team-name:
    description: 'Namespace of entity; used as namespace for --entity <namespace/kind/name>'
    required: false
  token:
    description: 'Personal Access token for webhook'
    required: false
runs:
  using: 'composite'
  steps:
    - name: check inputs
      run: |
        echo "${{ inputs.repository }}"
        echo "${{ inputs.descriptor-file }}"
        echo "${{ inputs.team-name }}"
      shell: bash
    - name: Dispatch and wait
      id: webhook
      uses: adityakar/workflow-dispatcher@a0f690a2262373956eaee3ef74a01f5afed4ec7c
      with:
        owner: 'department-of-veterans-affairs'
        repo: 'lighthouse-bandicoot-dev'
        token: ${{ inputs.token }}
        event_type: techdocs
        client_payload: '{ "repository": "${{ inputs.repository }}", "descriptor-file": "${{ inputs.descriptor-file }}", "team-name": "${{ inputs.team-name }}" }'
    # - name: Send webhook to initiate techdocs
    #   run: >
    #     curl -H "Accept: application/vnd.github.everest-preview+json"
    #     -H "Authorization: token ${{ inputs.token }}"
    #     --request POST
    #     --data
    #     '{ "event_type": "${{ inputs.event }}",
    #     "client_payload": {
    #     "sha": "${{ github.sha }}",
    #     "run_id": "${{ github.run_id }}",
    #     "run_number": "${{ github.run_number }}",
    #     "repository": "${{ inputs.repository }}",
    #     "descriptor-file": "${{ inputs.descriptor-file }}",
    #     "team-name": "${{ inputs.team-name }}"
    #     }}'
    #     https://api.github.com/repos/department-of-veterans-affairs/lighthouse-github-actions/dispatches
    #   shell: bash