name: "Send Techdocs Webhook"
description: "Sends a webhook to trigger repository dispatch event for techdocs workflow"
inputs:
  event:
    description: "Event trigger"
    default: "techdocs"
    required: false
  repository:
    description: "Name of repository"
    required: true
  branch:
    description: "Branch of repository"
    required: false
  descriptor-file:
    description: "Name of catalog entity descriptor file"
    required: false
  namespace:
    description: "Namespace of entity; used as namespace for --entity <namespace/kind/name>"
    default: "default"
    required: false
  token:
    description: "Personal Access token for webhook"
    required: false
  tag:
    description: "Tag or Commit sha for techdocs job version"
    default: "main"
    required: false
  gh-pages:
    description: "Flag used to enable gh-pages deployment"
    default: ""
    required: false
  strict-mode:
    description: "Flag used to enable or disable strict mode"
    default: "false"
    required: false
  enable-production:
    description: "Flag used to enable or disable techdocs for production"
    default: "true"
    required: false
runs:
  using: "composite"
  steps:
    - name: Dispatch TechDocs Workflow
      if: github.event.action != 'techdocs_ack'
      run: |
        curl -X POST https://api.github.com/repos/department-of-veterans-affairs/lighthouse-github-actions/dispatches \
        -H 'Accept: application/vnd.github.everest-preview+json' \
        -H 'Authorization: token ${{ inputs.token }}' \
        --data '{"event_type": "techdocs", "client_payload": { "repository": "${{ github.repository }}", "branch": "${{ inputs.branch }}"}}'
      shell: bash
    - name: Acknowledgement from TechDocs Repository
      if: github.event.action == 'techdocs_ack'
      run: |
        echo "Acknowledgement received from '${{ github.event.client_payload.repository }}'" && \
        curl -X POST https://api.github.com/repos/department-of-veterans-affairs/lighthouse-github-actions/dispatches \
        -H 'Accept: application/vnd.github.everest-preview+json' \
        -u 'Authorization: token ${{ inputs.token }}'' \
        --data '{"event_type": "ack", "client_payload": { "repository": "${{ github.repository }}", "branch": "${{ inputs.branch }}"}}'
      shell: bash