name: 'Send Techdocs Webhook'
description: 'Sends a webhook to trigger repository dispatch event for techdocs workflow'
inputs:
  event:
    description: 'Event trigger'
    required: false
    default: 'techdocs'
  repository:
    description: 'Name of repository'
    required: true
  descriptor-file:
    description: 'Name of catalog entity descriptor file'
    required: false
  team-name:
    description: 'Namespace of entity; used as namespace for --entity <namespace/kind/name>'
    required: false
  token:
    description: 'Personal Access token for webhook'
    required: false
runs:
  using: 'composite'
  steps:
    - name: run test-in-another-repo
      id: get_status
      uses: stinkyfingers/cross-repo-dispatch@52c5ff3cc7277612c058d932896ac665f77ec249
      with:
        owner: 'department-of-veterans-affairs'
        repo: 'lighthouse-github-actions'
        ref: 'main'
        pat: ${{ inputs.token }}
        user: ${{ github.repository_owner }}
        sha: ${{ github.sha }}
        event_type: 'techdocs'
        client_payload: '{ "repository": "${{ inputs.repository }}", "descriptor-file": "${{ inputs.descriptor-file }}", "team-name": "${{ inputs.team-name }}", "token": "${{ inputs.token }}" }'
        workflow_status_timeout: 1200
    - name: Display Results
      run: |
        echo "Status: ${{ steps.get_status.outputs.status }}"
        echo "Conclusion: ${{ steps.get_status.outputs.conclusion }}"
        echo "Html url: ${{ steps.get_status.outputs.html_url }}"
      shell: bash