name: Build & Publish Documentation
on:
  push:
    branches: [main]
    paths: ['**/*.md', '**/mkdocs.yaml']
  repository_dispatch:
    types: [techdocs]
  workflow_dispatch:
jobs:
  build-techdocs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [Development, Production]
    environment:
      name: ${{ matrix.environment }}
    steps:
      - name: ${{ github.event.client_payload.sha }}
        run: echo "${{ github.event.client_payload.sha }}"
      - name: Build techdocs
        uses: department-of-veterans-affairs/lighthouse-github-actions/.github/actions/techdocs@main
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          kube_namespace: ${{ secrets.KUBE_NAMESPACE }}
          serviceAccountName: bandicoot-sa
          repository: ${{ github.event.client_payload.repository != '' && github.event.client_payload.repository || github.repository }}
          descriptor-file: ${{ github.event.client_payload.descriptor-file }}
          namespace: ${{ github.event.client_payload.namespace != '' && github.event.client_payload.namespace || 'lighthouse-bandicoot-dev' }}
          token: ${{ github.event.client_payload.token != '' && github.event.client_payload.token || secrets.TECHDOCS_PAT }}
          AWSBucketName: ${{ secrets.AWS_BUCKET_NAME }}
          pat: ${{ secrets.TECHDOCS_PAT }}
  deploy-gh-pages:
    runs-on: ubuntu-latest
    container:
      image: zaslowd/techdocs
      # credentials:
      #   username: va-lighthouse-developer-hub
      #   password: ${{ secrets.TECHDOCS_PAT }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.client_payload.repository != '' && github.event.client_payload.repository || github.repository }}
          token: ${{ github.event.client_payload.token != '' && github.event.client_payload.token || secrets.TECHDOCS_PAT }}
      - name: Deploy Github Pages
        run: mkdocs gh-deploy --force
        shell: bash
