name: Build & publish documentation
on:
  repository_dispatch:
    types: [techdocs]
  push:
    branches: [main]
    paths: ["**/*.md", "**/mkdocs.yaml"]
  workflow_dispatch:
env:
  REPO: ${{ github.event.client_payload.repository != '' && github.event.client_payload.repository || github.repository }}
  TOKEN: ${{ github.event.client_payload.token != '' && github.event.client_payload.token || secrets.TECHDOCS_PAT }}
  NAMESPACE: ${{ github.event.client_payload.namespace != '' &&  github.event.client_payload.namespace || secrets.KUBE_NAMESPACE }}
jobs:
  validate-techdocs:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.client_payload.github }}
      - name: ${{ github.event.client_payload.sha }} # Used to return success or fail to the source repo
        run: echo "${{ github.event.client_payload.sha }}"
      - uses: actions/checkout@v3
        with:
          repository: ${{ env.REPO }}
          token: ${{ env.TOKEN }}
      - name: Validate techdocs
        id: validation
        uses: department-of-veterans-affairs/lighthouse-github-actions/.github/actions/validate-techdocs@main
        with:
          repository: ${{ env.REPO }}
          descriptor-file: ${{ github.event.client_payload.descriptor-file }}
          namespace: ${{ env.NAMESPACE }}
          token: ${{ env.TOKEN }}
          strict-mode: ${{ github.event.client_payload.strict-mode != '' && github.event.client_payload.strict-mode || 'true' }}
      - name: Validation results
        run: |
          echo "${{ steps.validation.outputs.results }}"
  build-techdocs:
    needs: [validate-techdocs]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [Development, Production]
    environment:
      name: ${{ matrix.environment }}
    steps:
      - name: ${{ github.event.client_payload.sha }}
        run: echo "${{ github.event.client_payload.sha }}"
      - name: Create techdocs
        uses: department-of-veterans-affairs/lighthouse-github-actions/.github/actions/techdocs@main
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          kube_namespace: ${{ secrets.KUBE_NAMESPACE }}
          serviceAccountName: bandicoot-sa
          repository: ${{ env.REPO }}
          descriptor-file: ${{ github.event.client_payload.descriptor-file }}
          namespace: ${{ env.NAMESPACE }}
          token: ${{ env.TOKEN }}
          AWSBucketName: ${{ secrets.AWS_BUCKET_NAME }}
          PAT: ${{ secrets.TECHDOCS_PAT }}
  deploy-gh-pages:
    if: ${{ github.event.client_payload.gh-pages == 'true' || github.event_name != 'repository_dispatch' }}
    needs: [validate-techdocs]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ env.REPO }}
          token: ${{ env.TOKEN }}
      - name: Install GraphViz
        run: sudo apt-get install -y graphviz
      - name: Setup Mkdocs dependencies
        run: /bin/sh <(curl -s https://${{ secrets.WEBHOOK_PAT }}@raw.githubusercontent.com/department-of-veterans-affairs/lighthouse-github-actions/main/scripts/setup_mkdocs.sh)
      - name: Deploy Github Pages
        run: mkdocs gh-deploy --force -r https://${{ env.TOKEN }}@github.com/${{ env.REPO }}.git
        shell: bash
