name: Build & publish documentation
on:
  repository_dispatch:
    types: [techdocs]
  push:
    branches: [main]
    paths: ["**/*.md", "**/mkdocs.yaml"]
  workflow_dispatch:
env:
  REPO: ${{ github.event.client_payload.repository != '' && github.event.client_payload.repository || github.repository }}
  TOKEN: ${{ github.event.client_payload.token != '' && github.event.client_payload.token || secrets.TECHDOCS_PAT }}
  NAMESPACE: ${{ github.event.client_payload.namespace != '' &&  github.event.client_payload.namespace || secrets.KUBE_NAMESPACE }}
jobs:
  build-techdocs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [Development, Production]
    environment:
      name: ${{ matrix.environment }}
    steps:
      - name: ${{ github.event.client_payload.sha }}
        run: echo "${{ github.event.client_payload.sha }}"
      - name: Create techdocs
        uses: department-of-veterans-affairs/lighthouse-github-actions/.github/actions/techdocs@main
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          kube_namespace: ${{ secrets.KUBE_NAMESPACE }}
          serviceAccountName: bandicoot-sa
          repository: $REPO
          descriptor-file: ${{ github.event.client_payload.descriptor-file }}
          namespace: $NAMESPACE
          token: $TOKEN
          AWSBucketName: ${{ secrets.AWS_BUCKET_NAME }}
          PAT: ${{ secrets.TECHDOCS_PAT }}
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: $REPO
          token: $TOKEN
      - name: Install GraphViz
        run: sudo apt-get install -y graphviz
      - name: Setup Mkdocs dependencies
        run: /bin/sh <(curl -s https://${{ secrets.WEBHOOK_PAT }}@raw.githubusercontent.com/department-of-veterans-affairs/lighthouse-developer-portal/main/scripts/setup_mkdocs.sh)
      - name: Deploy Github Pages
        run: mkdocs gh-deploy --force -r https://$TOKEN@github.com/$REPO.git
        shell: bash
