name: Build Techdocs Image

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-techdocs-image:
    name: Secure Release Pipeline
    uses: department-of-veterans-affairs/lighthouse-tornado-secrel-pipeline/.github/workflows/pipeline.yml@v1.1.0
    with:
      config-file: .github/secrel/techdocs-config.yml
    secrets: inherit
