name: CI/CD Workflow Example
on:
  workflow_dispatch:
jobs:
  create-techdocs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - name: Create techdocs
      uses: ./.github/actions/techdocs@main
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
        kube_namespace: 'lighthouse-bandicoot-dev'
        serviceAccountName: 'bandicoot-sa'