name: CI/CD Workflow Example
on:
  workflow_dispatch:
jobs:
  create-techdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Send deployment event via webhook
        uses: department-of-veterans-affairs/lighthouse-github-actions/.github/actions/techdocs-webhook@main
        with:
          repository: 'department-of-veterans-affairs/lighthouse-github-actions'