name: CI/CD Workflow Example
on:
  workflow_dispatch:
jobs:
  create-techdocs:
    name: Generate and Publish Techdocs
    uses: department-of-veterans-affairs/lighthouse-github-actions/.github/workflows/techdocs.yml@main
    with:
      kubeconfig: ${{ secrets.KUBE_CONFIG }}
      kube_namespace: 'lighthouse-bandicoot-dev'
      serviceAccountName: 'bandicoot-sa'
      repository: 'department-of-veterans-affairs/lighthouse-github-actions'
      team-name: 'lighthouse-bandicoot'