name: CI/CD Workflow Example
on:
  push:
    branches: [main]
    paths: ['docs/*']
  workflow_dispatch:
jobs:
  create-techdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Techdocs webhook
        uses: department-of-veterans-affairs/lighthouse-github-actions/.github/actions/techdocs-webhook@main
        with:
          repository: ${{ github.repository }}
          descriptor-file: 'catalog-info.yaml'
          token: ${{ secrets.WEBHOOK_PAT }}
