name: Create Techdocs
on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository name to run techdocs job with'
        required: true
      descriptor-file:
        description: 'Descriptor file for Entity(e.g. catalog-info.yaml)'
        required: false
      team-name:
        description: 'Team name; can be omitted if descriptor file includes .metadata.namespace'
        required: false
jobs:
  create-techdocs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
      with:
        ref: 'main'
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Create techdocs
      uses: department-of-veterans-affairs/lighthouse-github-actions/.github/actions/techdocs@main
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
        kube_namespace: 'lighthouse-bandicoot-dev'
        serviceAccountName: 'bandicoot-sa'
        repository: ${{ inputs.repository }}
        descriptor-file: ${{ inputs.descriptor-file }}
        team-name: ${{ inputs.team-name }}
    # - name: Compare workflows
    #   run: |
    #     echo "${{ github.sha }}"
    #     echo "${{ github.run_id }}"
    #     echo "${{ github.run_number }}"
    #     echo "${{ github.event.client_payload.sha }}"
    #     echo "${{ github.event.client_payload.run_id }}"
    #     echo "${{ github.event.client_payload.run_number }}"