name: Techdocs Test Suite

# Work in progress
# on:
#   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        namespace: ['', 'lighthouse-bandicoot-dev']
        serviceAccountName: ['', 'bandicoot-sa']
        repository: ['', 'department-of-veterans-affairs/should-fail']

    steps:
    - uses: actions/checkout@v2.4.0
    # Improve user experience by having user provide url to catalog-info.yaml and parse the yaml file for kind, name, team, and repository.
    - name: Test Techdocs 
      uses: department-of-veterans-affairs/lighthouse-github-actions/.github/actions/techdocs@main
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
        namespace: "lighthouse-bandicoot-dev"
        serviceAccountName: "bandicoot-sa"
        repository: "department-of-veterans-affairs/lighthouse-embark"
        team-name: "lighthouse-bandicoot"
        kind: "Component"
        