name: Create Techdocs
on:
  repository_dispatch:
    types: [techdocs]
  workflow_dispatch:
jobs:
  create-techdocs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
      with:
        ref: 'main'
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Create techdocs
      uses: department-of-veterans-affairs/lighthouse-github-actions/.github/actions/techdocs@main
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
        kube_namespace: 'lighthouse-bandicoot-dev'
        serviceAccountName: 'bandicoot-sa'
        repository: ${{ github.event.client_payload.repository }}
        descriptor-file: ${{ github.event.client_payload.descriptor-file }}
        team-name: ${{ github.event.client_payload.team-name }}
    - name: Compare workflows
      run: |
        echo "${{ github.sha }}"
        echo "${{ github.run_id }}"
        echo "${{ github.run_number }}"
        echo "${{ github.event.client_payload.sha }}"
        echo "${{ github.event.client_payload.run_id }}"
        echo "${{ github.event.client_payload.run_number }}"