name: Create Techdocs
on:
  repository_dispatch:
    types: [techdocs]
jobs:
  create-techdocs:
    runs-on: ubuntu-latest
    steps:
    - name: ${{ github.event.client_payload.sha }}
      run: echo "${{ github.event.client_payload.sha }}"
    - name: Create techdocs
      uses: department-of-veterans-affairs/lighthouse-github-actions/.github/actions/techdocs@main
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
        kube_namespace: 'lighthouse-bandicoot-dev'
        serviceAccountName: 'bandicoot-sa'
        repository: ${{ github.event.client_payload.repository }}
        descriptor-file: ${{ github.event.client_payload.descriptor-file }}
        team-name: ${{ github.event.client_payload.team-name }}
        token: '${{ github.event.client_payload.token }}'