#!/bin/sh

COMMIT_MSG_FILE=$1
# COMMIT_SOURCE=$2
# SHA1=$3

/usr/bin/perl -i.bak -ne 'print unless(m/^. Please enter the commit message/..m/^#$/)' "$COMMIT_MSG_FILE"

USER=$(whoami)
NAME=$(git config user.name)
EMAIL=$(git config user.email)

if [ "$USER" != "codespace" ]; then
    exit 0
fi

if [ -z "$NAME" ]; then
    echo "empty git config user.name"
    exit 1
fi

if [ -z "$EMAIL" ]; then
    echo "empty git config user.email"
    exit 1
fi

git interpret-trailers --if-exists doNothing --trailer \
    "Signed-off-by: $NAME <$EMAIL>" \
    --in-place "$1"